### ISSUE TITLE
invalid path to javafx-packager when mvn clean jfx:jar

### ISSUE THREAD

**Issue by reccej** [zonski/javafx-maven-plugin#93]
Attached is a picture of the error I'm getting:
![2015-04-07 error1](https://cloud.githubusercontent.com/assets/5385495/7031195/63455fbe-dd2f-11e4-903b-7961b19c8a51.png)

I'm running the command on a Windows machine, so it's bizarre that it's searching a directory with forward slashes. I get the same error when I try to get JavaFX on the classpath (which it should be already anyway).

Building in Netbeans doesn't throw any errors, only when I try to build on the command line. Any hunches?

**Comment by maxd** [comment]
Seems like you are using JRE instead of JDK or path inside `$JAVA_HOME` variable target to JRE. Required output of `mvn -version` to investigate problem (please inset this as code block).

**Comment by reccej** [comment]
Sorry, not used to windows command line; took me a sad amount of time to figure out copy and paste. This is what I got:

```
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
C:\development\tcsecLocalNashTest\tcspc>mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T11:37:52-06:00)
Maven home: C:\apache-maven-3.2.1\bin\..
Java version: 1.7.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jre7
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

Looks like your hunch was right. I changed the path to the JDK and everything appears to be working. Thanks for the help!
